version: "3.9"
services:
  database:
    image: postgres
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=postgres
      - DATABASE_HOST=database
    ports:
      - "3000:3000"
    depends_on:
      - database
