default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graph_ql_pet_development

test:
  <<: *default
  database: graph_ql_pet_test

production:
  <<: *default
  database: graph_ql_pet_production
  username: graph_ql_pet
  password: <%= ENV['GRAPH_QL_PET_DATABASE_PASSWORD'] %>
